# Visualize
***

"Visualisation is a fundamentally human activity. A good visualisation will show you things that you did not expect, or raise new questions about the data. A good visualisation might also hint that you're asking the wrong question, or you need to collect different data. Visualisations can surprise you, but don't scale particularly well because they require a human to interpret them."  
- Garrett Grolemund & Hadley Wickham, *R for Data Science*
***

## Flowcharts

`diagram`

`DiagrammeR`

***
## Interfaces

`shiny`

***
## Plots

`{base}`

* `abline`: Add straight lines to a plot.
* `plot`: Generic X-Y plotting.
* `points`: Add points to a plot.

`{ggbeeswarm}`

* `geom_beeswarm`: Create a beeswarm plot.

`ggplot2`

* `aes`: Construct aesthetic mappings.
  * Arguments include `color`, `fill`, `size`, `labels`, `alpha`, `shape` (1-20 accept color attributes and 21-25 accept color and fill attributes), `linewidth`, `linetype`, and `group`.
  * Use `?pch` to see options for `shape`.
  * The default shape for points does not have a `fill` attribute, which means that mapping a categorical variable onto `fill` won't result in multiple colors.
  * Helper functions to include in the call when needing to modify the data include: `stats::reorder`.
* `coord_*`
  * `coord_cartesian`: Zoom a plot in or out without changing the underlying data.
  * `coord_flip`: Flip the x and y axes.
  * `coord_polar`: Used to convert a stacked bar chart to a pie chart.
* `facet_*`
  * `facet_grid`: Lay out panels in a grid.
  * `facet_wrap`: Wrap a 1D ribbon of panels into 2D (observe a variable, conditional on another variable).
* `geom_*`: Create a geometry.
  * Note that `aes` can be called within `geom_*` rather than prior to.
  * `geom_abline`: Add reference lines to a plot.
  * `geom_bar`: Create a bar chart, where the height of the bar is proportional to the number of cases in each group.
  * `geom_boxplot`: Create a boxplot.
  * `geom_col`: Create a bar chart, where the height of the bar represents values in the data.
  * `geom_density`: Create a kernal density estimate (a smoothed version of a histogram).
    *  Consider using `geom_rug` with `geom_density` in order to be transparent about smoothed data.
  * `geom_dotplot`: Create a histogram out of dots.
  * `geom_histogram`: Create a histogram.
    *  Use `y = stat(density)` to rescale the y-axis from counts to a probability estimate.
  * `geom_hline`: Add a horizontal reference line to the plot.
  *`geom_jitter`: Jitter points.
    * Useful with `geom_boxplot`.
  * `geom_path`: Connect observations in the order in which they appear.
  * `geom_point`: Create a scatterplot (a.k.a. point chart or dot plot).
  * `geom_rug`: Create a ruge plot in the margin.
    * Useful with `geom_density`.
  * `geom_smooth`: Smoothed conditional means; aids the eye in seeing patterns in the presence of overplotting.
  * `geom_text`: Add text directly to the plot.
  * `geom_violin`: Create a violin plot.
  * `geom_vline`: Add a vertical reference line to the plot.
* `ggplot`: Create a plot.
* `ggtitle`: Modify the plot title.
* `group`: Specify groupings.
  * Used within `aes`. Note that `group` is usually unnecessary when specifying `color`, `shape`, `fill`, or `linetype` within `aes`, or when using facets. See ["Aesthetics: grouping"](https://ggplot2.tidyverse.org/reference/aes_group_order.html) for more information.
* `labs`: Modify axis, legend, and plot labels.
* `position_*`:
  * `position_identity`: Don't adjust position.
  * `position_dodge`: Dodge overlapping objects side-to-side.
  * `position_nudge`: Nudge points a fixed distance.
  * `position_stack`: Stack overlapping objects on top of each other, as counts.
  * `position_fill`: Stack overlapping objects on top of each other, as densities.
  * `position_jitter`: Jitter points to avoid overplotting.
  * `position_jitterdodge`: Simultaneously dodge and jitter.
* `scale_*_*`:
  * `scale_x_*`
  * `scale_y_*`
  * `scale_color_*`
  * `scale_fill_*`
  * `scale_shape_*`
  * `scale_size`
  * `scale_linetype_*`
* `stat_*`: Statistic layers (sometimes called by `geom_` layers).
  * `stat_bin`
  * `stat_bin2d`
  * `stat_bindot`
  * `stat_binhex`
  * `stat_boxplot`
  * `stat_contour`
  * `stat_quantile`
  * `stat_smooth`
  * `stat_sum`
 * `xlab`: Modify the label of the x-axis.
 * `ylab`: Modify the label of the y-axis.

`{ggridges}`

* `geom_density_ridges`: Create a ridgeline plot.

`{graphics}`

* `boxplot`: Create a box-and-whisker plot.
* `hist`: Create a histogram.
* `stripchart`: One dimensional scatter plots.
  * Preferable to `ggplot` when creating one-dimensional plots.

`{grDevices}`

* `colorRamp`: Color interpolation.
* `colorRampPalette`: Color interpolation.

`{RColorBrewer}`

* `brewer.pal`: Make the ColorBrewer color palettes available as R palattes.