# Visualize

"Visualisation is a fundamentally human activity. A good visualisation will show you things that you did not expect, or raise new questions about the data. A good visualisation might also hint that you're asking the wrong question, or you need to collect different data. Visualisations can surprise you, but don't scale particularly well because they require a human to interpret them."  
- Garrett Grolemund & Hadley Wickham, *R for Data Science*

References:

- [**A ggplot2 Tutorial for Beautiful Plotting in R](https://www.cedricscherer.com/2019/08/05/a-ggplot2-tutorial-for-beautiful-plotting-in-r/?utm_campaign=Data_Elixir&utm_source=Data_Elixir_370/)

## Interfaces

- `shiny`

## Graphs, Charts, and Plots

`{base}`

- `abline()`
  - Add straight lines to a plot.
- `plot()`
- `points()`

`{diagram}`

`{DiagrammeR}`

- `grViz()`

`{GGally}`

- `ggally_box()`
- `ggpairs()`
  - Scatter plot matrix (SPLOM).
- `ggparcoord()`
  - Parallel coordinate plots.

`{ggbeeswarm}`

- `geom_beeswarm()`

`{ggforce}`

- `facet_wrap_paginate()`

[`{ggplot2}`](https://www.rdocumentation.org/packages/ggplot2/versions/3.3.5)

- `aes()`
  - Arguments include `color`, `fill`, `size`, `labels`, `alpha`, `shape` (1-20 accept color attributes and 21-25 accept color and fill attributes), `linewidth`, `linetype`, and `group`.
  - Use `?pch` to see options for `shape` and `?points` to see options for points.
  - Note that `aes` can be called within `geom_*` rather than prior to.
  - The default shape for points does not have a `fill` attribute, which means that mapping a categorical variable onto `fill` won't result in multiple colors.
  - Helper functions to include in the call when needing to modify the data include: `stats::reorder()`.
- `coord_cartesian()`
- `coord_flip()`
- `coord_polar()`
  - Use to convert a stacked bar chart to a pie chart.
- `cut_number()`
- `element_*()`
- `facet_grid()`
  - `ROWS ~ COLS`: When using a tilde function, the variable on the left specifies the rows and the variable on the right specifies the columns. When faceting in only one direction (e.g., only on rows), use `.` to specify nothing for the unused direction.
- `facet_wrap()`
  - Wrap long panel names using `stringr::str_wrap()`: `facet_wrap(~str_wrap(var, width = xx))`.
  - Use `ggforce::facet_wrap_paginate()` when there are too many panels.
- `geom_abline()`
- `geom_bar()`
  - Create a bar chart, where the height of the bar is proportional to the number of cases in each group.
- `geom_boxplot()`
- `geom_col()`
  - Create a bar chart, where the height of the bar represents values in the data.
- `geom_count()`/`stat_sum()`
  - See `geom_jitter()` and `geom_point()`.
  - Use `ggplot2::scale_size()` to adjust point diameters.
- `geom_density()`
  - Create a kernal density estimate (a smoothed version of a histogram).
  - Consider using `ggplot2::geom_rug()` with `ggplot2::geom_density()` in order to be transparent about smoothed data.
- `geom_dotplot()`
  - Create a histogram out of dots.
- `geom_errorbar()`
  - Shortcut for `geom_bar(stat = "identity")`.
- `geom_freqpoly()`
  - See `ggplot2::geom_histogram()`.
- `geom_histogram()`
  - Use `aes(x, ..density..)` to rescale the y-axis from counts to frequency.
  - Use `y = stat(density)` to rescale the y-axis from counts to a probability estimate.
  - See `ggplot2::geom_freqpoly()`.
- `ggplot2::geom_hline()`
-`geom_jitter()`
  - Useful with `ggplot2::geom_boxplot()`.
  - See `geom_count()` and `geom_point()`.
- `geom_path()`
  - Connect observations in the order in which they appear.
- `geom_point()`
  - See `geom_count()` and `geom_jitter()`.
- `geom_quantile()`
- `geom_rug()`
  - Useful with `ggplot2::geom_density()`.
- `geom_segment()`
- `geom_smooth()`/`stat_smooth()`
  - For LOESS smoothing, the `span` argument adjusts the data window used for smoothing (the default values is 0.9).
  - Use a dummy group variable (e.g., `aes(group = 1))` or `aes(group = "All")`) to override groups specified in an earlier mapping layer and show the trend for the population.
- `geom_tile()`
  - Heat maps.
- `ggplot_build()`
  - Access calculated values.
- `ggtitle()`
- `group()`
  - Used within `aes()`. 
  - Note that `group` is usually unnecessary when specifying `color`, `shape`, `fill`, or `linetype` within `aes`, or when using facets. See ["Aesthetics: grouping"](https://ggplot2.tidyverse.org/reference/aes_group_order.html) for more information.
- `labs()`
<<<<<<< HEAD
  - Use the `color` argument to relabel the legend title.
=======
  - Modify axis, legend, and plot labels.
- `mean_cl_boot()`
- `mean_cl_normal()`
- `mean_sdl()`
  - Use with `ggplot2::stat_summary()` (e.g., `stat_summary(fun.data = mean_sdl, fun.args = list(mult = 1))`).
- `median_hilow()`
>>>>>>> 8610ad64bf4202523419e146372d231df592aea0
- `position_identity()`
  - Don't adjust position.
- `position_dodge()`
  - Dodge overlapping objects side-to-side.
- `position_nudge()`
  - Nudge points a fixed distance.
- `position_stack()`
  - Stack overlapping objects on top of each other, as counts.
- `position_fill()`
  - Stack overlapping objects on top of each other, as densities.
- Special variables:
  - `..prop..`: Calculates proportion of values (e.g., `stat_sum(aes(size = ..prop..))`).
- `stat_function()`
  - Compute `y` values from a function of `x` values.
- `stat_qq()`
  - Perform calculations for a quantile-quantile plot.
- `stat_qq_line()`
- `stat_summary()`
  - Summarize `y` values at distinct `x` values.
  - See `ggplot2::mean_*()`.
- `theme_*()`
  - See example for `grid::unit()`.
  - See `ggthemes` package.
- `theme_update()`
  - "When you call 'theme_update' and assign it to an object (e.g., called `old`), that object stores the *current* default theme, and the arguments *update* the default theme. If you want to restore the previous default theme, you can get it back by using `theme_update` again." -DataCamp

`{ggridges}`

- `geom_density_ridges()`
  - Create a ridgeline plot.

[`{ggthemes}`](https://www.rdocumentation.org/packages/ggthemes/versions/3.5.0)

`{graphics}`

- `boxplot()`
- `hist()`
- `par()`
- `stripchart()`
  - One dimensional scatter plots.
  - Prefer over `ggplot2::ggplot()` when creating one-dimensional plots.
  
`{grDevices}`

- `colorRamp()`
  - Color interpolation.
- `colorRampPalette()`
  - Color interpolation.

`{grid}`

- `unit()`
  - Create a `unit` object, to specify locations and dimensions in a coordinate system.
  - See example below.
  
`{plotly}`

- `plot_ly()`

`{RColorBrewer}`

- `brewer.pal()`
  - Make the ColorBrewer color palettes available as R palettes.

[`{stats}`](https://www.rdocumentation.org/packages/stats/versions/3.6.2)

- `biplot()`

### Examples

`grid::unit()`

```{r, eval=FALSE}
# Increase spacing between facets in a `ggplot` object:

plot + 
  theme(
    panel.spacing.x = unit(2, "cm"),
    panel.margin = unit(c(1, 2, 1, 1), "cm"))
```
