# Model

***
"Models are complementary tools to visualisation. Once you have made your questions sufficiently precise, you can use a model to answer them. Models are a fundamentally mathematical or computational tool, so they generally scale well. ... But every model makes assumptions, and by its very nature a model cannot question its own assumptions. That means a model cannot fundamentally surprise you. 
- Garrett Grolemund & Hadley Wickham, *R for Data Science*"

***
## General

`{base}`

* `sample`: Random samples and permutations.

`{dplyr}`

* `sample_n`: Sample n rows from a table.
    
`{stats}`

* `coef`: Extract model coefficients.
* `cor`: Correlation.
* `cov`: Covariance.
* `cov2cor`: Scale a covariance matrix into a correlation matrix.
* `var`: Variance.

***
## Regression

`{broom}`

* `augment`: Augment data with information from an object.
* `glance`: Construct a single row summary of a model, fit, or other object.
* `tidy`: Turn an object into a tidy tibble.

`{stats}`

* `df.residual`: Get the residual degrees of freedom.
* `lm`: Fit linear models.
* `p.adjust`: Adjust p-values for multiple comparisons.
* `residuals`: Extract model residuals.

`{tidyr}`

* `nest`: Nest repeated values in a list-variable.
  * Helpful when separating a data frame in preparation to model the data for each grouping.

***
## Simulation & Prediction

`base`

* `set.seed()`: Random number generation.

`stats`

* `predict()`: Model prediction.
    + Use with "lm" class objects and new data to predict new values (e.g., `predict(model, newdata)`).
* `rnorm()`: Generate a normal distribution.

***
## Strings

`base`

* `agrep()`: Approximate string matching (fuzzy matching).

`fuzzyjoin`

* `stringdist_join()`: Join two tables based on fuzzy string matching of their columns.
    + Child functions: `stringdist_inner_join()`, `stringdist_left_join()`, `stringdist_right_join()`, `stringdist_full_join()`, `stringdist_semi_join()`, `stringdist_anti_join()`.

`fuzzywuzzyR`

* `FuzzMatcher()`: Fuzzy character string matching (ratios).