# Referenced Packages
***
## A-D

[`anytime`](https://CRAN.R-project.org/package=anytime): Date converter.

[`assertive`](https://CRAN.R-project.org/package=assertive): Check functions to ensure code integrity.

[`base`](https://www.rdocumentation.org/packages/base/versions/3.5.1): Base R functions.

[`bookdown`](https://CRAN.R-project.org/package=bookdown): Author books and technical documents with R Markdown.
    + See Yihui Xie's [*bookdown: Authoring Books and Technical Documents with R Markdown*](https://bookdown.org/yihui/bookdown/).

[`broom`](https://CRAN.R-project.org/package=broom): Convert statistical analysis objects into tidy data frames.

[`car`](https://CRAN.R-project.org/package=car): Companion to applied regression.

[`chron`](https://CRAN.R-project.org/package=chron): Chronological objects which can handle dates and times.

[`countrycode`](https://CRAN.R-project.org/package=countrycode): Convert country names and country codes.

[`data.table`](https://CRAN.R-project.org/package=data.table): For large data.

[`DBI`](https://CRAN.R-project.org/package=DBI){#DBI}: Database interface.

* For MySQL documentation, see the [MySQL Reference Manual](https://dev.mysql.com/).
    
* Use with the `odbc` package.

[`diagram`](https://CRAN.R-project.org/package=diagram): Visualize simple graphs (networks); create plot flow diagrams.

[`DiagrammeR`](https://CRAN.R-project.org/package=DiagrammeR): Graph/network visualization.
    + DiagrammeR uses the [GraphViz](https://www.graphviz.org/) language.

[`dplyr`](https://CRAN.R-project.org/package=dplyr): Data manipulation.

* See also [dplyr.tidyverse.org](https://dplyr.tidyverse.org/).

***
## E-H

[`fasttime`](https://CRAN.R-project.org/package=fasttime): Fast utilit function for time parsing and conversion.

[`forcats`](https://CRAN.R-project.org/package=forcats): Tools for working with categorical variables.

[`fuzzyjoin`](https://CRAN.R-project.org/package=fuzzyjoin): Join tables together on inexact matching.

[`fuzzywuzzyR`](https://CRAN.R-project.org/package=fuzzywuzzyR): Fuzzy string matching.

[`gdata`](https://CRAN.R-project.org/package=gdata): Data manipulation.

[`ggbeeswarm`](https://CRAN.R-project.org/package=ggbeeswarm): Categorical scatter plots (violin and beeswarm).

[`ggplot2`](https://CRAN.R-project.org/package=ggplot2): Create elegant data visualizations.

[`ggridges`](https://CRAN.R-project.org/package=ggridges): Ridgeline plots in `ggplot2`.

[`graphics`](https://www.rdocumentation.org/packages/graphics/versions/3.5.1): R functions for base graphics.

[`grDevices`](https://www.rdocumentation.org/packages/grDevices/versions/3.5.2): Grahpics devices and support for base and grid graphics.

[`hms`](https://CRAN.R-project.org/package=hms): Times without dates.

[`httr`](https://CRAN.R-project.org/package=httr): Tools for working with HTTP.

***
## I-L

[`installr`](https://CRAN.R-project.org/package=installr): Install and update stuff (such as R, Rtools, Rstudio, Git).

[`janitor`](https://CRAN.R-project.org/package=janitor): Simple tools for examining and cleaning dirty data.

[`jsonlite`](https://CRAN.R-project.org/package=jsonlite): A robust, high performance JSON parser and generator.

[`knitr`](https://CRAN.R-project.org/package=knitr): Dynamic report generation in R using Literate Programming techniques.
    + See Yihui Xie's [*knitr*](http://yihui.name/knitr/).

[`lubridate`](https://CRAN.R-project.org/package=lubridate): Functions to work with date-times and time-spans.

* `lubridate` uses character formatting similar to `strptime()`, though there are some differences. To see `lubridate`'s formatting, type `?parse_date_time` into the R Console.

***
## M-P

[`magrittr`](https://CRAN.R-project.org/package=magrittr): Forward-pipe operator for R.

[`methods`](https://www.rdocumentation.org/packages/methods/versions/3.5.1): Formal methods and classes.

[`mgcv`](https://CRAN.R-project.org/package=mgcv): Mixed GAM computational vehicle with automatic smoothness estimation.

[`microbenchmark`](https://CRAN.R-project.org/package=microbenchmark): Measure and compare the execution time of R expressions.

[`odbc`](https://CRAN.R-project.org/package=odbc): Connect to ODBC compatible databases using the DBI Interface.

['openintro'](https://CRAN.R-project.org/package=openintro): Data sets and supplemental functions from OpenIntro textbooks.

[`packrat`](https://CRAN.R-project.org/package=packrat): Manage and document the versions of packages used in an R program.

* `packrat` tends to cause more trouble than it prevents, so avoid using it unless necessary or until it is improved.

[`pryr`](https://CRAN.R-project.org/package=pryr): Tools to pry back the covers of R and understand the language at a deeper level.

[`purrr`](https://CRAN.R-project.org/package=purrr): Functional programming tools.

* See also [purr.tidyverse.org](https://purrr.tidyverse.org/).

***
## Q-T

[`qdap`](https://CRAN.R-project.org/package=qdap): Bridging the gap between qualitative data and quantitative analysis (text mining).

[`qdapDictionaries`](https://CRAN.R-project.org/package=qdapDictionaries): Dictionaries and word lists for the `qdap` package.

[`RColorBrewer`](https://CRAN.R-project.org/package=RColorBrewer): ColorBrewer palattes.

[`readr`](https://CRAN.R-project.org/package=readr): Read rectangular text data.

* See also [readr.tidyverse.org](https://readr.tidyverse.org/).

[`readxl`](https://CRAN.R-project.org/package=readxl): Read Excel files.

[`rjson`](https://CRAN.R-project.org/package=rjson): Convert between R and JSON objects.

[`rlang`](https://CRAN.R-project.org/package=rlang): Functions for base types and Core R and Tidyverse features.

[`RMarkdown`](https://CRAN.R-project.org/package=rmarkdown): Save and execute code; generate high quality reports.

  * See also ["R Markdown: The Definitive Guide"](https://bookdown.org/yihui/rmarkdown/)).

[`scales`](https://CRAN.R-project.org/package=scales): Scale functions for visualization.

[`shiny`](https://CRAN.R-project.org/package=shiny): Web application framework.

[`splitstackshape`]( https://CRAN.R-project.org/package=splitstackshape): Stack and reshape datasets after splitting concatenated values.

[`stats`](https://www.rdocumentation.org/packages/stats/versions/3.5.1): Statistical functions.

[`stringr`](https://CRAN.R-project.org/package=stringr): Working with strings.

* See also [stringr.tidyverse.org](https://stringr.tidyverse.org/)).

[`svDialogs`](https://CRAN.R-project.org/package=svDialogs): Dialog boxes for Windows, MacOS, and Linuxes.

[`tcltk`](https://www.rdocumentation.org/packages/tcltk/versions/3.5.2): Interface and languate bindings to Tcl/Tk GUI elements.

[`tibble`](https://CRAN.R-project.org/package=tibble): Simple data frames with stricter checking and better formatting than the traditional data frame.

[`tidyr`](https://CRAN.R-project.org/package=tidyr): Tidy data.

* See also [tidyr.tidyverse.org](https://tidyr.tidyverse.org/).

[`tinytex`](https://CRAN.R-project.org/package=tinytex): Compile LaTeX Documents.
  + Required to compile and build a `bookdown` book.
  + See https://yihui.name/tinytex/

***
## U-Z

[`utils`](https://CRAN.R-project.org/package=R.utils): Various programming utilities.

[`XLConnect`](https://CRAN.R-project.org/package=XLConnect): Read, write, and format Excel data.

[`xts`](https://CRAN.R-project.org/package=xts): Provide for uniform handling of R's different time-based data classes by extending zoo.

[`zeallot`](https://CRAN.R-project.org/package=zeallot): Multiple, unpacking, and destructuring assignment.

[`zoo`](https://CRAN.R-project.org/package=zoo): For regular and irregular time series.