--- 
title: "R Reference Manual"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
always_allow_html: yes
---
# Introduction

In *R for Data Science*, Garrett Grolemund and Hadley Wickham outline the tools needed to tackle about 80% of the tasks required in a typical data science project ("[Introduction](https://r4ds.had.co.nz/introduction.html)"). Those tools, illustrated in the diagram below and the organizing template for this reference manual, are: 

* Import
* Tidy
* Transform
* Visualize
* Model
* Communicate
* Program

```{r, echo=FALSE}
DiagrammeR::grViz(" 

digraph {

graph [rankdir = LR;
       compound = TRUE;
       nodesep = 1]

subgraph cluster0 {
  style = rounded;
  label = Program;
  labeljust = center;
  node [color = white];

  Import; Tidy; Communicate

  subgraph cluster1 {
    style = rounded;
    bgcolor = lightgrey;
    label = Understand;
    labeljust = center;
    node [color = lightgrey];

    Transform -> Visualize -> Model -> Transform;

    {rank = same; Model; Visualize}
  }
  
  Import -> Tidy -> Transform;

  edge [headport = w]
  {Model; Visualize} -> Communicate [ltail = cluster1]
}
}")
```

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```